// Builds src/lib/desk/adm1-data.ts from public/yemen-adm1.geojson: each
// governorate's outline, rounded to ~1 km, so the server can tell which
// governorate a point lies in without reading public/ at runtime.
import { readFileSync, writeFileSync } from "node:fs";

const g = JSON.parse(readFileSync("public/yemen-adm1.geojson", "utf8"));
const r = (v) => Math.round(v * 100) / 100;
const out = g.features.map((f) => {
  const polys = f.geometry.type === "Polygon" ? [f.geometry.coordinates] : f.geometry.coordinates;
  const rings = polys.map((p) => {
    const ring = [];
    for (const [x, y] of p[0]) {
      const pt = [r(x), r(y)];
      const last = ring[ring.length - 1];
      if (!last || last[0] !== pt[0] || last[1] !== pt[1]) ring.push(pt);
    }
    return ring;
  }).filter((ring) => ring.length >= 4);
  return { iso: f.properties.shapeISO, rings };
});
writeFileSync(
  "src/lib/desk/adm1-data.ts",
  "/** Generated by scripts/build-adm1.mjs from public/yemen-adm1.geojson. Do not edit. */\n" +
    "export const ADM1: { iso: string; rings: [number, number][][] }[] = " + JSON.stringify(out) + ";\n",
);
console.log(out.length, "governorates");
