// Builds src/lib/desk/control-data.ts from public/control.json (edited by hand)
// and the district names in public/yemen-adm2.geojson, so the server knows the
// control picture without reading public/ at runtime. Runs before every build.
import { readFileSync, writeFileSync } from "node:fs";

const control = JSON.parse(readFileSync("public/control.json", "utf8"));
const names = new Map(
  JSON.parse(readFileSync("public/yemen-adm2.geojson", "utf8")).features.map((f) => [f.properties.id, f.properties]),
);
const rows = Object.entries(control.districts).map(([id, d]) => {
  const p = names.get(id);
  if (!p) throw new Error(`control.json names an unknown district: ${id}`);
  return { id, name: p.name, gov: p.gov, side: d.side, ...(d.since ? { since: d.since } : {}), ...(d.note ? { note: d.note } : {}) };
});
writeFileSync(
  "src/lib/desk/control-data.ts",
  "/** Generated by scripts/build-control.mjs from public/control.json. Do not edit. */\n" +
    `export const CONTROL_AS_OF = ${JSON.stringify(control.asOf)};\n` +
    "export const CONTROL: { id: string; name: string; gov: string; side: string; since?: string; note?: string }[] = " +
    JSON.stringify(rows) + ";\n",
);
console.log(rows.length, "districts with their own control");
