// Builds src/lib/desk/control-data.ts from public/control.json (edited by hand)
// and the district names in public/yemen-adm2.geojson, so the server knows the
// control picture without reading public/ at runtime. Runs before every build.
import { readFileSync, writeFileSync } from "node:fs";

const control = JSON.parse(readFileSync("public/control.json", "utf8"));
// Every district not listed takes its governorate's control (public/data.json).
const govControl = Object.fromEntries(
  JSON.parse(readFileSync("public/data.json", "utf8")).governorates
    .filter((g) => g.id.startsWith("YE-"))
    .map((g) => [g.id, g.control === "mixed" ? "contested" : g.control]),
);
const names = new Map(
  JSON.parse(readFileSync("public/yemen-adm2.geojson", "utf8")).features.map((f) => [f.properties.id, f.properties]),
);
const rows = Object.entries(control.districts).map(([id, d]) => {
  const p = names.get(id);
  if (!p) throw new Error(`control.json names an unknown district: ${id}`);
  return { id, name: p.name, gov: p.gov, side: d.side, ...(d.since ? { since: d.since } : {}), ...(d.note ? { note: d.note } : {}) };
});
writeFileSync(
  "src/lib/desk/control-data.ts",
  "/** Generated by scripts/build-control.mjs from public/control.json. Do not edit. */\n" +
    `export const CONTROL_AS_OF = ${JSON.stringify(control.asOf)};\n` +
    "export const CONTROL: { id: string; name: string; gov: string; side: string; since?: string; note?: string }[] = " +
    JSON.stringify(rows) + ";\n" +
    `export const GOV_CONTROL: Record<string, string> = ${JSON.stringify(govControl)};\n`,
);
console.log(rows.length, "districts with their own control");

// The districts' outlines (outer rings), so the server can tell which district
// a pin falls in rather than which district centre it is nearest to.
const shapes = JSON.parse(readFileSync("public/yemen-adm2.geojson", "utf8")).features.map((f) => {
  const g = f.geometry;
  const polys = g.type === "Polygon" ? [g.coordinates] : g.coordinates;
  // About a kilometre is enough to place a pin; repeated points go.
  const r2 = (v) => Math.round(v * 100) / 100;
  const ring = (r) => r.map(([a, b]) => [r2(a), r2(b)]).filter((pt, i, all) => i === 0 || pt[0] !== all[i - 1][0] || pt[1] !== all[i - 1][1]);
  return [f.properties.id, polys.map((p) => ring(p[0])).filter((r) => r.length >= 4)];
});
writeFileSync(
  "src/lib/desk/adm2-shapes.ts",
  "/** Generated by scripts/build-control.mjs from public/yemen-adm2.geojson. Do not edit. */\n" +
    "export const ADM2_SHAPES: [string, [number, number][][]][] = " + JSON.stringify(shapes) + ";\n",
);

// The hand corrections to map pins (public/map-fixes.json), so the developments'
// and fronts' maps leave out a removed pin and move a wrong one, as the main map does.
const fixes = JSON.parse(readFileSync("public/map-fixes.json", "utf8")).fixes || {};
const pinFixes = Object.fromEntries(
  Object.entries(fixes)
    .filter(([, f]) => f.remove || typeof f.lat === "number" || f.side)
    .map(([fp, f]) => [fp, f.remove ? { remove: true } : { ...(typeof f.lat === "number" ? { lat: f.lat, lng: f.lng } : {}), ...(f.place ? { place: f.place } : {}), ...(f.side ? { side: f.side } : {}) }]),
);
writeFileSync(
  "src/lib/desk/map-fixes-data.ts",
  "/** Generated by scripts/build-control.mjs from public/map-fixes.json. Do not edit. */\n" +
    "export const MAP_FIXES: Record<string, { remove?: true; lat?: number; lng?: number; place?: string; side?: string }> = " + JSON.stringify(pinFixes) + ";\n",
);
console.log(Object.keys(pinFixes).length, "map pin fixes for the developments' maps");
