/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IranConflictDeskRouteImport } from './routes/iran-conflict-desk'
import { Route as YemenRouteImport } from './routes/yemen'
import { Route as YemenConflictDeskRouteImport } from './routes/yemen-conflict-desk'
import { Route as ApiBriefRouteImport } from './routes/api/brief'
import { Route as ApiDeskRouteImport } from './routes/api/desk'
import { Route as ApiScanRouteImport } from './routes/api/scan'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as ApiTgmediaRouteImport } from './routes/api/tgmedia'
import { Route as ApiTickRouteImport } from './routes/api/tick'
import { Route as YemenConflictDeskMethodologyRouteImport } from './routes/yemen-conflict-desk_.methodology'
import { Route as YemenConflictDeskSourcesRouteImport } from './routes/yemen-conflict-desk_.sources'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IranConflictDeskRoute = IranConflictDeskRouteImport.update({
  id: '/iran-conflict-desk',
  path: '/iran-conflict-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const YemenRoute = YemenRouteImport.update({
  id: '/yemen',
  path: '/yemen',
  getParentRoute: () => rootRouteImport,
} as any)
const YemenConflictDeskRoute = YemenConflictDeskRouteImport.update({
  id: '/yemen-conflict-desk',
  path: '/yemen-conflict-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBriefRoute = ApiBriefRouteImport.update({
  id: '/api/brief',
  path: '/api/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeskRoute = ApiDeskRouteImport.update({
  id: '/api/desk',
  path: '/api/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanRoute = ApiScanRouteImport.update({
  id: '/api/scan',
  path: '/api/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTgmediaRoute = ApiTgmediaRouteImport.update({
  id: '/api/tgmedia',
  path: '/api/tgmedia',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTickRoute = ApiTickRouteImport.update({
  id: '/api/tick',
  path: '/api/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const YemenConflictDeskMethodologyRoute =
  YemenConflictDeskMethodologyRouteImport.update({
    id: '/yemen-conflict-desk_/methodology',
    path: '/yemen-conflict-desk/methodology',
    getParentRoute: () => rootRouteImport,
  } as any)
const YemenConflictDeskSourcesRoute =
  YemenConflictDeskSourcesRouteImport.update({
    id: '/yemen-conflict-desk_/sources',
    path: '/yemen-conflict-desk/sources',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/iran-conflict-desk': typeof IranConflictDeskRoute
  '/yemen': typeof YemenRoute
  '/yemen-conflict-desk': typeof YemenConflictDeskRoute
  '/api/brief': typeof ApiBriefRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/scan': typeof ApiScanRoute
  '/api/search': typeof ApiSearchRoute
  '/api/status': typeof ApiStatusRoute
  '/api/tgmedia': typeof ApiTgmediaRoute
  '/api/tick': typeof ApiTickRoute
  '/yemen-conflict-desk/methodology': typeof YemenConflictDeskMethodologyRoute
  '/yemen-conflict-desk/sources': typeof YemenConflictDeskSourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/iran-conflict-desk': typeof IranConflictDeskRoute
  '/yemen': typeof YemenRoute
  '/yemen-conflict-desk': typeof YemenConflictDeskRoute
  '/api/brief': typeof ApiBriefRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/scan': typeof ApiScanRoute
  '/api/search': typeof ApiSearchRoute
  '/api/status': typeof ApiStatusRoute
  '/api/tgmedia': typeof ApiTgmediaRoute
  '/api/tick': typeof ApiTickRoute
  '/yemen-conflict-desk/methodology': typeof YemenConflictDeskMethodologyRoute
  '/yemen-conflict-desk/sources': typeof YemenConflictDeskSourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/iran-conflict-desk': typeof IranConflictDeskRoute
  '/yemen': typeof YemenRoute
  '/yemen-conflict-desk': typeof YemenConflictDeskRoute
  '/api/brief': typeof ApiBriefRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/scan': typeof ApiScanRoute
  '/api/search': typeof ApiSearchRoute
  '/api/status': typeof ApiStatusRoute
  '/api/tgmedia': typeof ApiTgmediaRoute
  '/api/tick': typeof ApiTickRoute
  '/yemen-conflict-desk_/methodology': typeof YemenConflictDeskMethodologyRoute
  '/yemen-conflict-desk_/sources': typeof YemenConflictDeskSourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/iran-conflict-desk'
    | '/yemen'
    | '/yemen-conflict-desk'
    | '/api/brief'
    | '/api/desk'
    | '/api/scan'
    | '/api/search'
    | '/api/status'
    | '/api/tgmedia'
    | '/api/tick'
    | '/yemen-conflict-desk/methodology'
    | '/yemen-conflict-desk/sources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/iran-conflict-desk'
    | '/yemen'
    | '/yemen-conflict-desk'
    | '/api/brief'
    | '/api/desk'
    | '/api/scan'
    | '/api/search'
    | '/api/status'
    | '/api/tgmedia'
    | '/api/tick'
    | '/yemen-conflict-desk/methodology'
    | '/yemen-conflict-desk/sources'
  id:
    | '__root__'
    | '/'
    | '/iran-conflict-desk'
    | '/yemen'
    | '/yemen-conflict-desk'
    | '/api/brief'
    | '/api/desk'
    | '/api/scan'
    | '/api/search'
    | '/api/status'
    | '/api/tgmedia'
    | '/api/tick'
    | '/yemen-conflict-desk_/methodology'
    | '/yemen-conflict-desk_/sources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IranConflictDeskRoute: typeof IranConflictDeskRoute
  YemenRoute: typeof YemenRoute
  YemenConflictDeskRoute: typeof YemenConflictDeskRoute
  ApiBriefRoute: typeof ApiBriefRoute
  ApiDeskRoute: typeof ApiDeskRoute
  ApiScanRoute: typeof ApiScanRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiStatusRoute: typeof ApiStatusRoute
  ApiTgmediaRoute: typeof ApiTgmediaRoute
  ApiTickRoute: typeof ApiTickRoute
  YemenConflictDeskMethodologyRoute: typeof YemenConflictDeskMethodologyRoute
  YemenConflictDeskSourcesRoute: typeof YemenConflictDeskSourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iran-conflict-desk': {
      id: '/iran-conflict-desk'
      path: '/iran-conflict-desk'
      fullPath: '/iran-conflict-desk'
      preLoaderRoute: typeof IranConflictDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yemen': {
      id: '/yemen'
      path: '/yemen'
      fullPath: '/yemen'
      preLoaderRoute: typeof YemenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yemen-conflict-desk': {
      id: '/yemen-conflict-desk'
      path: '/yemen-conflict-desk'
      fullPath: '/yemen-conflict-desk'
      preLoaderRoute: typeof YemenConflictDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brief': {
      id: '/api/brief'
      path: '/api/brief'
      fullPath: '/api/brief'
      preLoaderRoute: typeof ApiBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desk': {
      id: '/api/desk'
      path: '/api/desk'
      fullPath: '/api/desk'
      preLoaderRoute: typeof ApiDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan': {
      id: '/api/scan'
      path: '/api/scan'
      fullPath: '/api/scan'
      preLoaderRoute: typeof ApiScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tgmedia': {
      id: '/api/tgmedia'
      path: '/api/tgmedia'
      fullPath: '/api/tgmedia'
      preLoaderRoute: typeof ApiTgmediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tick': {
      id: '/api/tick'
      path: '/api/tick'
      fullPath: '/api/tick'
      preLoaderRoute: typeof ApiTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yemen-conflict-desk_/methodology': {
      id: '/yemen-conflict-desk_/methodology'
      path: '/yemen-conflict-desk/methodology'
      fullPath: '/yemen-conflict-desk/methodology'
      preLoaderRoute: typeof YemenConflictDeskMethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yemen-conflict-desk_/sources': {
      id: '/yemen-conflict-desk_/sources'
      path: '/yemen-conflict-desk/sources'
      fullPath: '/yemen-conflict-desk/sources'
      preLoaderRoute: typeof YemenConflictDeskSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IranConflictDeskRoute: IranConflictDeskRoute,
  YemenRoute: YemenRoute,
  YemenConflictDeskRoute: YemenConflictDeskRoute,
  ApiBriefRoute: ApiBriefRoute,
  ApiDeskRoute: ApiDeskRoute,
  ApiScanRoute: ApiScanRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiStatusRoute: ApiStatusRoute,
  ApiTgmediaRoute: ApiTgmediaRoute,
  ApiTickRoute: ApiTickRoute,
  YemenConflictDeskMethodologyRoute: YemenConflictDeskMethodologyRoute,
  YemenConflictDeskSourcesRoute: YemenConflictDeskSourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
